language: c
sudo: true
before_install:
  - nm --version
git:
  depth: 1
matrix:
  include:
    - os: osx
      compiler: gcc
      osx_image: xcode9.4
      env: CXX=gcc
    - os: osx
      compiler: clang
      osx_image: xcode9.4
      env: CXX=clang
    - os: osx
      compiler: gcc
      osx_image: xcode9.2
      env: CXX=gcc
    - os: osx
      compiler: clang
      osx_image: xcode9.2
      env: CXX=clang
    - os: osx
      compiler: gcc
      osx_image: xcode8
      env: CXX=gcc
    - os: osx
      compiler: clang
      osx_image: xcode8
      env: CXX=clang
script:
  - make
  - (cd tests && ./basic_tests.sh)
